name: SonarQube CI
on: push
jobs:
  sonarQubeTrigger:
    name: SonarQube Trigger
    # if: github.repository_owner == 'Uninett'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: SonarQube Scan
        uses: kitabisa/sonarqube-action@v1.1.0
        with:
          host: "https://sonarqube.software.geant.org"
          login: ${{ secrets.SONARQUBE_TOKEN }}
